/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CheckboxQuestion: typeof import('./src/components/CheckboxQuestion.vue')['default']
    DropdownQuestion: typeof import('./src/components/DropdownQuestion.vue')['default']
    InputQuestion: typeof import('./src/components/InputQuestion.vue')['default']
    QuestionCard: typeof import('./src/components/QuestionCard.vue')['default']
    RadioQuestion: typeof import('./src/components/RadioQuestion.vue')['default']
    RatingQuestion: typeof import('./src/components/RatingQuestion.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonLoading: typeof import('./src/components/SkeletonLoading.vue')['default']
    StatusPage: typeof import('./src/components/StatusPage.vue')['default']
  }
}
